name: Trigger Lambda Redeploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger rebuild and redeploy workflow
        uses: actions/github-script@v7
        env:
          ENGINE_PAT: ${{ secrets.ENGINE_PAT }}
        with:
          script: |
            const axios = require('axios');
            const repo = 'cmu-dsc/poker-backend-2025';
            const token = process.env.ENGINE_PAT;
            
            await axios({
              method: 'post',
              url: `https://api.github.com/repos/${repo}/actions/workflows/deploy-match-lambda.yml/dispatches`,
              headers: {
                Authorization: `token ${token}`,
              },
              data: {
                ref: 'main',
              },
            });
